#pragma once


enum eScene { LOGO_SCENE, STAGE1_SCENE ,BOSS_SCENE,END_SCENE};
enum OBJECT_TYPE
{
	OBJECT_PLAYERATTACKEFFECT,
	OBJECT_PLAYER,
	OBJECT_PLAYERATTACKEFFECT2,
	OBJECT_HELPER,
	OBJECT_MONSTER,
	OBJECT_BULLET,
	OBJECT_MONSTER_BULLET,
	OBJECT_STAGEOBJECT,
	OBJECT_IMMORTALITY,
	OBJECT_EFFECT,
	OBJECT_ITEM,
	OBJECT_UI,
	OBJECT_END 
};
enum OBJECT_STATE {MOVE_LEFT,MOVE_RIGHT,MOVE_UP,MOVE_DOWN};


enum STATEPLAYER
{
	IDLE_GAMESTART_RIGHT,
	IDLE_RIGHT,
	WALK_RIGHT,
	IDLE_ATTACK_RIGHT,
	REINFORCE_ATTACK_RIGHT,
	WALK_ATTACK_RIGHT,
	DASH_RIGHT,
	DASH_ATTACK_RIGHT,
	DASH_STOP_RIGHT,
	JUMP_RIGHT,
	JUMP_ATTACK_RIGHT,
	IDLE_GAMESTART_LEFT,
	IDLE_LEFT,
	WALK_LEFT,
	IDLE_ATTACK_LEFT,
	REINFORCE_ATTACK_LEFT,
	WALK_ATTACK_LEFT,
	DASH_LEFT,
	DASH_ATTACK_LEFT,
	DASH_STOP_LEFT,
	JUMP_LEFT,
	JUMP_ATTACK_LEFT
};

enum GUNMAN
{
	GUNMAN_IDLE_RIGHT,
	GUNMAN_IDLE_LEFT,
	GUNMAN_IDLE_WALK_RIGHT,
	GUNMAN_IDLE_WALK_LEFT,
	GUNMAN_ATTACK_RIGHT,
	GUNMAN_ATTACK_LEFT
};

enum ROLLING
{
	ROLLING_IDLE_RIGHT,
	ROLLING_IDLE_LEFT,
	ROLLING_IDLE_ROLLING_ATTACK_RIGHT,
	ROLLING_IDLE_ROLLING_ATTACK_LEFT,
	ROLLING_IDLE_ROLLING_ATTACK_RIGHT_STOP,
	ROLLING_IDLE_ROLLING_ATTACK_LEFT_STOP,
	ROLLING_RIGHT_LEFT,
	ROLLING_LEFT_RIGHT
};

enum Stage01Boss
{
	STAGE01BOSS_START_RIGHT,
	STAGE01BOSS_START_LEFT,
	STAGE01BOSS_IDLE_RIGHT,
	STAGE01BOSS_IDLE_LEFT,
	STAGE01BOSS_IDLE_WALK_RIGHT,
	STAGE01BOSS_IDLE_WALK_LEFT,
	STAGE01BOSS_ATTACK01_RIGHT,
	STAGE01BOSS_ATTACK01_LEFT
};