#pragma once


enum eScene { LOGO_SCENE, STAGE1_SCENE ,END_SCENE};
enum OBJECT_TYPE
{
	OBJECT_PLAYER,
	OBJECT_HELPER,
	OBJECT_MONSTER,
	OBJECT_BULLET,
	OBJECT_MONSTER_BULLET,
	OBJECT_EFFECT,
	OBJECT_UI,
	OBJECT_ITEM,
	OBJECT_END 
};
enum OBJECT_STATE {MOVE_LEFT,MOVE_RIGHT,MOVE_UP,MOVE_DOWN};